# Generated by Django 6.0 on 2026-01-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0002_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="rating",
            field=models.FloatField(default=4.0),
        ),
    ]
