# Generated by Django 6.0 on 2026-01-12 16:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0003_movie_rating"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movie",
            options={"ordering": ["-release_date"]},
        ),
        migrations.AddField(
            model_name="booking",
            name="customer_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="booking",
            name="customer_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="booking",
            name="seats",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="booking",
            name="show_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="format",
            field=models.CharField(
                choices=[("2D", "2D"), ("3D", "3D"), ("IMAX", "IMAX"), ("4DX", "4DX")],
                default="2D",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="is_now_showing",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="poster_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="release_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="duration",
            field=models.IntegerField(
                blank=True, help_text="Duration in minutes", null=True
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="genre",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Action", "Action"),
                    ("Comedy", "Comedy"),
                    ("Drama", "Drama"),
                    ("Thriller", "Thriller"),
                    ("Sci-Fi", "Sci-Fi"),
                    ("Horror", "Horror"),
                    ("Romance", "Romance"),
                    ("Adventure", "Adventure"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("English", "English"),
                    ("Hindi", "Hindi"),
                    ("Telugu", "Telugu"),
                    ("Tamil", "Tamil"),
                    ("Kannada", "Kannada"),
                    ("Malayalam", "Malayalam"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="rating",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
